CREATE TABLE places (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   PLACES_NAME NVARCHAR(50) NOT NULL
);

CREATE TABLE categories (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   CATEGORIE_NAME NVARCHAR(50) NOT NULL
);

CREATE TABLE admins (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   LOGIN_NAME NVARCHAR(50) NOT NULL,
   LOGIN_PASSWORD NVARCHAR(200) NOT NULL,
   SAULT NVARCHAR(500) NOT NULL,
   TOKEN NVARCHAR(500) NOT NULL
);

CREATE TABLE accounters (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   LOGIN_NAME NVARCHAR(50) NOT NULL,
   LOGIN_PASSWORD NVARCHAR(200) NOT NULL,
   SAULT NVARCHAR(500) NOT NULL,
   TOKEN NVARCHAR(500) NOT NULL
);

CREATE TABLE users (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   LOGIN_NAME NVARCHAR(50) NOT NULL,
   LOGIN_PASSWORD NVARCHAR(200) NOT NULL,
   SAULT NVARCHAR(500) NOT NULL,
   TOKEN NVARCHAR(500) NOT NULL
);

CREATE TABLE user_profiles (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   USER_ID INT NOT NULL,
   FIRST_NAME NVARCHAR(100) NOT NULL,
   LAST_NAME NVARCHAR(100) NOT NULL,
   EMAIL NVARCHAR(50) NOT NULL,
   FOREIGN KEY (USER_ID) REFERENCES users (ID) on delete cascade on update cascade
);

CREATE TABLE companies (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   LOGIN_NAME NVARCHAR(50) NOT NULL,
   LOGIN_PASSWORD NVARCHAR(200) NOT NULL,
   SAULT NVARCHAR(500) NOT NULL,
   TOKEN NVARCHAR(500) NOT NULL
);

CREATE TABLE company_profiles (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   COMPANY_ID INT NOT NULL,
   COMPANY_NAME NVARCHAR(100) NOT NULL,
   ADRESS NVARCHAR(500) NOT NULL,
   MOL NVARCHAR(50) NOT NULL,
   EIK NVARCHAR(20) NOT NULL,
   EMAIL NVARCHAR(50) NOT NULL,
   COMPANY_TYPE NVARCHAR (100) NOT NULL,
   STATUS INT NOT NULL,
   FOREIGN KEY (COMPANY_ID) REFERENCES companies (ID) on delete cascade on update cascade
);

CREATE TABLE owner (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   COMPANY_NAME NVARCHAR(100) NOT NULL,
   ADRESS NVARCHAR(500) NOT NULL,
   MOL NVARCHAR(50) NOT NULL,
   EIK NVARCHAR(20) NOT NULL,
   EMAIL NVARCHAR(50) NOT NULL,
   IBAN NVARCHAR(50) NOT NULL,
   BIC NVARCHAR(20) NOT NULL,
   PHONE_NUMBER NVARCHAR(20) NOT NULL
);

CREATE TABLE advertisements (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CATEGORY_ID INT NOT NULL,
	TITLE NVARCHAR(100) NOT NULL,
   COMPANY_ID INT NOT NULL,
   CONTENT NVARCHAR(4000) NOT NULL,
   TEST NVARCHAR(4000),
   PRICE DOUBLE NOT NULL,
   ACTIVITY_DAYS INT NOT NULL,
   EXPIRATION_DATE DATE,
   PLACE_ID INT NOT NULL,
   IS_VIP BOOLEAN NOT NULL,
   IS_APPROVED BOOLEAN NOT NULL,
   IS_PAID BOOLEAN NOT NULL,
   IS_EXPIRED BOOLEAN NOT NULL,
   FOREIGN KEY (CATEGORY_ID) REFERENCES  categories (ID) on delete cascade on update cascade,
   FOREIGN KEY (COMPANY_ID) REFERENCES company_profiles (ID) on delete cascade on update cascade,
   FOREIGN KEY (PLACE_ID) REFERENCES places (ID) on delete cascade on update cascade
);

CREATE TABLE INVOICES (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	INVOICE_DATE DATE NOT NULL,
   OWNER_ID INT NOT NULL,
   COMPANY_ID INT NOT NULL,
   ADV_ID INT NOT NULL,
   QUANTITY DOUBLE NOT NULL,
   DISCOUNT DOUBLE NOT NULL,
   PRICE DOUBLE NOT NULL,
   TAX DOUBLE NOT NULL,
   TAX_AMMOUNT DOUBLE NOT NULL,
   TOTAL_PRICE DOUBLE NOT NULL,
   EVENT_DATE DATE NOT NULL,
   LATE_PAYMENT INT NOT NULL,
   IS_CASH BOOLEAN NOT NULL,
   IS_PAYED BOOLEAN NOT NULL,
   DUE_PAYMENT BOOLEAN NOT NULL,
   FOREIGN KEY (OWNER_ID) REFERENCES  OWNER (ID) on update cascade,
   FOREIGN KEY (COMPANY_ID) REFERENCES company_profiles (ID) on delete cascade on update cascade
);

alter table INVOICES auto_increment=1000000001;